### ISSUE TITLE
Images are public

### ISSUE THREAD

**Issue by kishorebolt03** [0xdedinfosec/0xdedinfosec.github.io#1]
All the HTB machine images are public
Even if you hide the pages with root hash i can see the images from this repository

**Comment by 0xdedinfosec** [comment]
working on that bro thinking how to fix that if you have any idea tell me

**Comment by 0xdedinfosec** [comment]
Now the issue is fixed in the writeup spider

**Comment by kishorebolt03** [comment]
Nice 👍👍👍
